### PR TITLE
Fix indentation and code folding

### PR DESCRIPTION
**Pull request by prometheas**
Bad indentation in `test/test.js` was breaking code folding in my editor, so I fixed that and added both .editorconfig settings _and_ minimal ESlint rules to prevent this from happening again.

### CODE REVIEW

**Comment by prometheas** [comment]
Any thoughts on this one?

It's mostly to fix code folding in the file, but figured I'd through in a minimal amount of linting rules to help keep things on the rails for future commits (I use [Hound](http://houndci.com) in some of my repositories to automatically apply linting to inbound PRs—it's free for OSS projects, and I can recommend it).

**Comment by prometheas** [comment]
Any feedback? 😉

**Comment by prometheas** [comment]
Just fixed a conflict that emerged since my initial submission.

Please LMK if there's anything further I can do to get this correction accepted.

**Comment by prometheas** [comment]
Folks, I have literally got no idea who owns this, but it'd be lovely to get some feedback on either this work, or recommendations around how to (more properly?) engage with the team to fix the problem at hand.

**Comment by aeschli** [comment]
Thanks a lot @prometheas, I merged your changes. Sorry for the waiting.

**Pull request merged**
