### PR TITLE
Template consistency pass

### LINKED ISSUE #359: Do a consistency pass on extension templates
As I've been making some PRs recently I've noticed that there are minor inconsistencies across the various extension templates such as:

- Inconsistent capitalization (i.e. sometimes `CMD` is used and other times `Cmd` is used)
- Inconsistent usage of "VS Code" versus "VSCode" (I believe brand guidelines say it should always be "VS Code")
- Inconsistent usage of periods at the end of bullet list items
- Other bits and pieces

If addressing this sounds desirable, I would be happy to contribute a PR that does a pass on these types of things and generally adds some polish to the extension templates.

### PR DESCRIPTION
**Pull request by hawkticehurst**
Resolves #359 

Includes the following changes:

- Fix capitalization in the root `package.json` description
- Remove extra empty line from `gitattributes` files
- Update all `gitignore`, `gitattribute`, and `vscodeignore` that are not dotfiles to be dotfiles
- Change all instances of `CMD` to `Cmd`
- Change all instances of 'VSCode' to 'VS Code'
- Update template `README` files to be more consistent with each other in terms of formatting and content
- Fix various typos, formatting, and grammar issues in `vsc-extension-quickstart` files

### CODE REVIEW

**Comment by hawkticehurst** [comment]
cc @daviddossett / @misolori / @aeschli

**Comment by hawkticehurst** [comment]
Looks like CI testing failed because `gitattribute` (no dotfile) is part of the test suite (so I'm happy to revert my changes on that).

But I suppose it's a good time to double-check why only some of `gitignore`, `gitattribute`, and `vscodeignore` files are dotfiles and others are not?

**Comment by aeschli** [comment]
> Update all gitignore, gitattribute, and vscodeignore that are not dotfiles to be dotfiles

That also requires updating the generator scripts. Note: the user never saw the dotless files.

**Review by aeschli — APPROVED** [review]

**Review by mjbvz — APPROVED** [review]

**Comment by hawkticehurst** [comment]
> That also requires updating the generator scripts. Note: the user never saw the dotless files.

Ahh, thanks for clarifying and for contributing a change to address this!

**Pull request merged**
