### PR TITLE
Add Prettier support

### PR DESCRIPTION
**Pull request by felipecrs**

### CODE REVIEW

**Comment by felipecrs** [comment]
Before moving ahead and run `prettier` on all the files, I want to hear the opinion from the maintainers. :)

**Comment by aeschli** [comment]
The change to use `eslint:recommended` is good, but using prettier over our built-in TypeScript formatter is for each developer to decide. We don't want to propagate that in the vscode yeoman generator

**Comment by aeschli** [comment]
I looked into adding `eslint:recommended` and `plugin:@typescript-eslint/recommended` but there's a couple of rules that we need to disable (@typescript-eslint/no-empty-function", @typescript-eslint/no-explicit-any) for our small extension sample.

I think we better stick to the small set of rules we have and let users tune it by themselves.

**Comment by felipecrs** [comment]
@aeschli for `eslint:recommended` and `plugin:@typescript-eslint/recommended` so we simply add those rules. Why not?

**Comment by felipecrs** [comment]
@aeschli why not let the user decide at the generation time wheter to use Prettier or not? It's much more powerful than the builtin formatter.

**Pull request closed without merging**
