### PR TITLE
Use extensionParam for extension pack

### PR DESCRIPTION
**Pull request by MrLuje**
Allows to create an "Extension Pack" with yo cli without any prompt

Today, the question "Add the currently installed extensions to the extension pack?" must be answered manually, I used the param _extensionParam_ for this question

`yo code --extensionType extensionpack --extensionName nodejs-pack --extensionParam y`

### CODE REVIEW

**Comment by aeschli** [comment]
@sandy081 Can you review that one?

**Comment by sandy081** [comment]
@MrLuje Not sure what is the feature that you are trying to add. Can you please explain or give an example.

**Comment by MrLuje** [comment]
@sandy081 It allows to create an "Extension Pack" with yo cli without any prompt

Today, the question "Add the currently installed extensions to the extension pack?" must be answered manually, I used the param *extensionParam* for this question

`
yo code --extensionType extensionpack --extensionName nodejs-pack --extensionParam y
`

BTW, sorry about the missing description, probably created the PR too fast..

**Comment by sandy081** [comment]
@aeschli Since it is an argument on `yo code` leaving it to your decision to support it or not.

**Pull request merged**
